---
- name: Install/configure solr server
  hosts: "{{host_inventory}}"
  become: true
  roles:
    - ensure-interfaces-up
    - setup-web-proxy
    - { role: install-packages, package_list: ["java-1.8.0-openjdk", "java-1.8.0-openjdk-devel"] }
    - dn-solr
