# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- block:
  - name: Run the install script
    command: "{{full_solr_dir}}/init/systemd/install.sh"
  - name: Restart the systemctl daemon
    command: systemctl daemon-reload
  become: true
