# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- block:
  - name: Modify the install script to comment-out service enablement/startup
    replace:
      dest: "{{full_solr_dir}}/init/systemd/install.sh"
      regexp: "{{item}}"
      replace: '\g<1>#\g<2>'
    with_items:
      - "^(.*)(systemctl enable.*)$"
      - "^(.*)(systemctl start.*)$"
      - "^(.*)(systemctl status.*)$"
  - name: Run the install script
    command: "{{full_solr_dir}}/init/systemd/install.sh"
  - name: Modify permissions on the fusion distribution directory
    file:
      dest: "{{solr_dir}}"
      owner: "{{solr_user}}"
      group: "{{solr_group}}"
      recurse: yes
  - name: Restart the systemctl daemon
    command: systemctl daemon-reload
  become: true
